[project]
name = "youtubedataanalyzer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.6",
    "mplcursors>=0.7",
    "pandas>=2.3.3",
    "plotly>=6.3.1",
    "pyqt5>=5.15.11",
]
